### ISSUE TITLE
Update tree with current timepoints

### ISSUE THREAD

**Issue by andrewhill157** [CSE512-15S/a3-tdurham-ajh24-chiasson#1]
Currently, the tree is loaded all at once in an interactively expandable way. Ideally, it should expand to show only the cells up to the current time point.

**Comment by tdurham86** [comment]
I was able to get code working to change the color of the nodes in sync with the time point progression. I also tried setting the node visibility, which works, but it doesn't look very good. We need to have the "node opening" or "cell dividing" object constancy to make it work, otherwise the appearance of nodes is just too abrupt/jarring. I tried searching around for a way to set the xy coordinates of the nodes in advance, which might then allow us to use the tree layout's native node-opening animation to accomplish this, but I haven't been successful yet.

**Comment by andrewhill157** [comment]
Nice progress! How is the speed performance on your end? Works here, but is currently pretty slow as far as I can tell.

**Comment by andrewhill157** [comment]
One thought -- if it would help to have the this change fade in rather than just making the points visible, this should be possible with Jquery I think.

**Comment by tdurham86** [comment]
Speed is good; I'm pretty sure that the nodes on the tree are highlighted right at the time point in which the parent cell divides. What were you seeing that was slow?

Fading in would help, but I still think we need the "cell dividing" animation to match the 3D plot.

**Comment by andrewhill157** [comment]
So the speed when playing the movie looks fine, it is mostly when I jump around using the slider that stuff gets slow as far as I can tell.

**Comment by tdurham86** [comment]
Ah, I see. Yep, you're right. If you jump a whole bunch of time points using the slider the node coloring does get very slow.

**Comment by andrewhill157** [comment]
Your most recent commit (89d54754dafe0dcd508849bdfaec490e356408a6) makes performance way better, nice job! I noticed that near the end of development a few nodes start disappearing on the tree (and possibly in the embryo?) -- perhaps a slight bug.

For me this also seems to have broken highlighting -- I assume that this is due to changes in the underlying data structure or something.

**Comment by tdurham86** [comment]
I think I did have some highlighting bugs in there. Check my most recent commit, the highlighting in the embryo should be fixed and I took a first step toward highlighting in the tree.

**Comment by andrewhill157** [comment]
Lineage highlighting is working now (highlighting in the tree looks cool and multiple highlights also seem to work!), but highlighting something like muscle, for example, seems broken still. 

I think that highlighting the current cells from that lineage is great. Would it also make sense to highlight the lineage as a whole in some way (in a different way to the most recent cells -- maybe less opaque or something idk) for future improvements?

**Comment by andrewhill157** [comment]
Near the end of the movie and when the movie reaches the end and loops back still have some weirdness going on as far as I can tell. For the former, take a look at the MSaaa lineage as an example.

**Comment by andrewhill157** [comment]
One thing I noticed as well is that if you remove highlighting and it is the last highlight, the highlighting on the tree does not get removed. Minor bug, just wanted to log for future reference.

**Comment by tdurham86** [comment]
I think all of the issues here have been resolved. There are still some cells that disappear from the tree towards the end of the time series. This happens because there are some unidentified nuclei that must be daughters of the disappearing cells. Essentially, the known nuclei disappear, their unknown daughters come in, and there is no way to tell that the parents of these unidentified nuclei should be visible when redrawing the tree at subsequent time points. I can talk with Pete to see if we can identify these nuclei (or use a time series in which all nuclei are identified), but I will open a new issue for that one.
